#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable spamass-milter.service

  if test ! -f "disabled.bin"; then
    echo "antispam is already enabled."
  else
    rm "disabled.bin"
    if systemctl is-active --quiet spamass-milter-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart spamass-milter-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart spamass-milter.service
    else
      echo "antispam will be enabled on next reboot."
    fi
  fi

fi

